### ISSUE TITLE
Unstable Mongoose package

### ISSUE THREAD

**Issue by fmoliveira** [heroku-examples/node-articles-nlp#15]
I've just cloned the repository, did `$ npm install` and tried to run everything with node foreman, and I've had a bunch of warnings about an unstable Mongoose version, resulting later in an undefined property error. This has blocked me from running the example application.

```
$ nf start
[WARN] No ENV file found
[OKAY] Trimming display Output to 118 Columns
8:42:46 AM web.1  |  { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
8:42:46 AM web.1  |  js-bson: Failed to load c++ bson extension, using pure JS version
8:42:46 AM worker.1 |  { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
8:42:46 AM worker.1 |  js-bson: Failed to load c++ bson extension, using pure JS version
8:42:46 AM web.1  |
8:42:46 AM web.1  |  ##############################################################
8:42:46 AM web.1  |  #
8:42:46 AM web.1  |  #   !!! MONGOOSE WARNING !!!
8:42:46 AM web.1  |  #
8:42:46 AM web.1  |  #   This is an UNSTABLE release of Mongoose.
8:42:46 AM web.1  |  #   Unstable releases are available for preview/testing only.
8:42:46 AM web.1  |  #   DO NOT run this in production.
8:42:46 AM web.1  |  #
8:42:46 AM web.1  |  ##############################################################
8:42:46 AM web.1  |
8:42:46 AM worker.1 |
8:42:46 AM worker.1 |  ##############################################################
8:42:46 AM worker.1 |  #
8:42:46 AM worker.1 |  #   !!! MONGOOSE WARNING !!!
8:42:46 AM worker.1 |  #
8:42:46 AM worker.1 |  #   This is an UNSTABLE release of Mongoose.
8:42:46 AM worker.1 |  #   Unstable releases are available for preview/testing only.
8:42:46 AM worker.1 |  #   DO NOT run this in production.
8:42:46 AM worker.1 |  #
8:42:46 AM worker.1 |  ##############################################################
8:42:46 AM worker.1 |
8:42:46 AM worker.1 |  { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
8:42:46 AM worker.1 |  js-bson: Failed to load c++ bson extension, using pure JS version
8:42:47 AM web.1  |  { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
8:42:47 AM web.1  |  js-bson: Failed to load c++ bson extension, using pure JS version
8:42:47 AM worker.1 |
8:42:47 AM worker.1 |  ##############################################################
8:42:47 AM worker.1 |  #
8:42:47 AM worker.1 |  #   !!! MONGOOSE WARNING !!!
8:42:47 AM worker.1 |  #
8:42:47 AM worker.1 |  #   This is an UNSTABLE release of Mongoose.
8:42:47 AM worker.1 |  #   Unstable releases are available for preview/testing only.
8:42:47 AM worker.1 |  #   DO NOT run this in production.
8:42:47 AM worker.1 |  #
8:42:47 AM worker.1 |  ##############################################################
8:42:47 AM worker.1 |
8:42:47 AM web.1  |
8:42:47 AM web.1  |  ##############################################################
8:42:47 AM web.1  |  #
8:42:47 AM web.1  |  #   !!! MONGOOSE WARNING !!!
8:42:47 AM web.1  |  #
8:42:47 AM web.1  |  #   This is an UNSTABLE release of Mongoose.
8:42:47 AM web.1  |  #   Unstable releases are available for preview/testing only.
8:42:47 AM web.1  |  #   DO NOT run this in production.
8:42:47 AM web.1  |  #
8:42:47 AM web.1  |  ##############################################################
8:42:47 AM web.1  |
8:42:47 AM worker.1 |  type=info msg="starting worker" concurrency=1
8:42:47 AM worker.1 |  type=info msg=connected service=rabbitmq
8:42:47 AM worker.1 |  type=info msg=connected service=mongodb
8:42:47 AM worker.1 |  d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\base.js:246
8:42:47 AM worker.1 |          throw message;
8:42:47 AM worker.1 |                ^
8:42:47 AM worker.1 |  TypeError: Cannot read property 'length' of undefined
8:42:47 AM worker.1 |      at processResults (d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1581:31…
8:42:47 AM worker.1 |      at d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1619:20
8:42:47 AM worker.1 |      at d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1157:7
8:42:47 AM worker.1 |      at d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1890:9
8:42:47 AM worker.1 |      at Server.Base._callHandler (d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\con…
8:42:47 AM worker.1 |      at d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:481:18 8:42:47 AM worker.1 |      at MongoReply.parseBody (d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\respons…
8:42:47 AM worker.1 |      at null.<anonymous> (d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\…
8:42:47 AM worker.1 |      at emit (events.js:107:17)
8:42:47 AM worker.1 |      at null.<anonymous> (d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\…
[DONE] Killing all processes with signal  null
8:42:47 AM worker.1 Exited Successfully
8:42:47 AM web.1  |  type=info msg="starting server" concurrency=1 thrifty=false timeout= busy_ms=
8:42:47 AM web.1  |  type=info msg=connected service=rabbitmq
8:42:47 AM web.1  |  type=info msg=connected service=mongodb
8:42:47 AM web.1  |  d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\base.js:246
8:42:47 AM web.1  |          throw message;
8:42:47 AM web.1  |                ^
8:42:47 AM web.1  |  TypeError: Cannot read property 'length' of undefined
8:42:47 AM web.1  |      at processResults (d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1581:31…

8:42:47 AM web.1  |      at d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1619:20
8:42:47 AM web.1  |      at d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1157:7
8:42:47 AM web.1  |      at d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1890:9
8:42:47 AM web.1  |      at Server.Base._callHandler (d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\con…

8:42:47 AM web.1  |      at d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:481:18
8:42:47 AM web.1  |      at MongoReply.parseBody (d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\respons…

8:42:47 AM web.1  |      at null.<anonymous> (d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\…

8:42:47 AM web.1  |      at emit (events.js:107:17)
8:42:47 AM web.1  |      at null.<anonymous> (d:\Repos\node-articles-nlp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\…

8:42:47 AM web.1  Exited Abnormally
```

**Comment by fmoliveira** [comment]
The mongoose package is declared in package.json as `"mongoose": "^3.8.13"`, which resolved to version 3.9.7, which seems to be an unstable version from mongoose. I haven't found the release neither the branch in their GitHub repo, so, I'm assuming it's a version nobody should be running.

I've changed mongoose version in package json to `"mongoose": "~3.8.13"`, which now resolves to version 3.8.31 and runs just fine. Now I can run the example application successfully.

**Comment by fmoliveira** [comment]
Here you go a PR that solves this. :smiley:

**Comment by fmoliveira** [comment]
@zeke @hunterloftis 
Here you go a PR that resolves this.

**Comment by rahul-desai3** [comment]
I faced the same issue. I installed mongoose v3.8.31 and now it works fine.

@maintainers: You guys should have this version in your `package.json` already.

-Rahul

**Comment by fmoliveira** [comment]
Please merge this @hunterloftis , it'll help a lot of people to get started to Heroku through the examples. :+1:

**Comment by fmoliveira** [comment]
Thanks a lot @hunterloftis ! :wink:
