### ISSUE TITLE
Failed at the node-production@0.0.0 start script 'nf start'

### ISSUE THREAD

**Issue by hwbrill** [heroku-examples/node-articles-nlp#25]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle node-production@0.0.0~prestart: node-production@0.0.0
6 silly lifecycle node-production@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle node-production@0.0.0~start: node-production@0.0.0
8 verbose lifecycle node-production@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle node-production@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/hwbrill/node-articles-nlp/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/ignition:/usr/local/ignition
10 verbose lifecycle node-production@0.0.0~start: CWD: /Users/hwbrill/node-articles-nlp
11 silly lifecycle node-production@0.0.0~start: Args: [ '-c', 'nf start' ]
12 info lifecycle node-production@0.0.0~start: Failed to exec start script
13 verbose stack Error: node-production@0.0.0 start: `nf start`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:885:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid node-production@0.0.0
15 verbose cwd /Users/hwbrill/node-articles-nlp
16 error Darwin 15.6.0
17 error argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "start"
18 error node v7.4.0
19 error npm  v4.0.5
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error node-production@0.0.0 start: `nf start`
24 error spawn ENOENT
25 error Failed at the node-production@0.0.0 start script 'nf start'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the node-production package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     nf start
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs node-production
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls node-production
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by hwbrill** [comment]
This went away once I ran npm install, the Getting Started section from the Asynchronous Web-Worker Model Using RabbitMQ in Node learning module didn't indicate performing a npm install but npm start....  But... Still have a problem with an error after performing npm start....
Error: Cannot find module '../build/Release/bson'
