### ISSUE TITLE
Error: Cannot find module '../build/Release/bson'

### ISSUE THREAD

**Issue by hwbrill** [heroku-examples/node-articles-nlp#26]
Herbs-iMac:node-articles-nlp hwbrill$ npm start

> node-production@0.0.0 start /Users/hwbrill/node-articles-nlp
> nf start

[OKAY] Loaded ENV .env File as KEY=VALUE Format
[OKAY] Trimming display Output to 93 Columns
7:37:56 PM web.1  |  { Error: Cannot find module '../build/Release/bson'
7:37:56 PM web.1  |  at Function.Module._resolveFilename (module.js:470:15)
7:37:56 PM web.1  |  at Function.Module._load (module.js:418:25)
7:37:56 PM web.1  |  at Module.require (module.js:498:17)
7:37:56 PM web.1  |  at require (internal/module.js:20:19)
7:37:56 PM web.1  |  at Object.<anonymous> (/Users/hwbrill/node-articles-nlp/node_modules/bson/ext/index.js:15…
7:37:56 PM web.1  |  at Module._compile (module.js:571:32)
7:37:56 PM web.1  |  at Object.Module._extensions..js (module.js:580:10)
7:37:56 PM web.1  |  at Module.load (module.js:488:32)
7:37:56 PM web.1  |  at tryModuleLoad (module.js:447:12)
7:37:56 PM web.1  |  at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
7:37:56 PM web.1  |  js-bson: Failed to load c++ bson extension, using pure JS version
7:37:56 PM worker.1 |  { Error: Cannot find module '../build/Release/bson'
7:37:56 PM worker.1 |  at Function.Module._resolveFilename (module.js:470:15)
7:37:56 PM worker.1 |  at Function.Module._load (module.js:418:25)
7:37:56 PM worker.1 |  at Module.require (module.js:498:17)
7:37:56 PM worker.1 |  at require (internal/module.js:20:19)
7:37:56 PM worker.1 |  at Object.<anonymous> (/Users/hwbrill/node-articles-nlp/node_modules/bson/ext/index.js:15…
7:37:56 PM worker.1 |  at Module._compile (module.js:571:32)
7:37:56 PM worker.1 |  at Object.Module._extensions..js (module.js:580:10)
7:37:56 PM worker.1 |  at Module.load (module.js:488:32)
7:37:56 PM worker.1 |  at tryModuleLoad (module.js:447:12)
7:37:56 PM worker.1 |  at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
7:37:56 PM worker.1 |  js-bson: Failed to load c++ bson extension, using pure JS version
7:37:56 PM worker.1 |  { Error: Cannot find module '../build/Release/bson'
7:37:56 PM worker.1 |  at Function.Module._resolveFilename (module.js:470:15)
7:37:56 PM worker.1 |  at Function.Module._load (module.js:418:25)
7:37:56 PM worker.1 |  at Module.require (module.js:498:17)
7:37:56 PM worker.1 |  at require (internal/module.js:20:19)
7:37:56 PM worker.1 |  at Object.<anonymous> (/Users/hwbrill/node-articles-nlp/node_modules/bson/ext/index.js:15…
7:37:56 PM worker.1 |  at Module._compile (module.js:571:32)
7:37:56 PM worker.1 |  at Object.Module._extensions..js (module.js:580:10)
7:37:56 PM worker.1 |  at Module.load (module.js:488:32)
7:37:56 PM worker.1 |  at tryModuleLoad (module.js:447:12)
7:37:56 PM worker.1 |  at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
7:37:56 PM worker.1 |  js-bson: Failed to load c++ bson extension, using pure JS version
7:37:57 PM web.1  |  { Error: Cannot find module '../build/Release/bson'
7:37:57 PM web.1  |  at Function.Module._resolveFilename (module.js:470:15)
7:37:57 PM web.1  |  at Function.Module._load (module.js:418:25)
7:37:57 PM web.1  |  at Module.require (module.js:498:17)
7:37:57 PM web.1  |  at require (internal/module.js:20:19)
7:37:57 PM web.1  |  at Object.<anonymous> (/Users/hwbrill/node-articles-nlp/node_modules/bson/ext/index.js:15…
7:37:57 PM web.1  |  at Module._compile (module.js:571:32)
7:37:57 PM web.1  |  at Object.Module._extensions..js (module.js:580:10)
7:37:57 PM web.1  |  at Module.load (module.js:488:32)
7:37:57 PM web.1  |  at tryModuleLoad (module.js:447:12)
7:37:57 PM web.1  |  at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
7:37:57 PM web.1  |  js-bson: Failed to load c++ bson extension, using pure JS version
7:37:57 PM worker.1 |  type=info msg="starting worker" concurrency=1
7:37:57 PM worker.1 |  type=info msg=connected service=rabbitmq
7:37:57 PM web.1  |  type=info msg="starting server" concurrency=1 thrifty=false timeout= busy_ms=
7:37:57 PM web.1  |  type=info msg=connected service=rabbitmq

**Comment by hwbrill** [comment]
resolved:
node-articles-nlp/node_modules/bson/README.md file indicates the current build is located in the 'browser_build/bson.js' file.  So changed the bson require statement from '../build/Release/bson' to '../browser_build/bson' in line 10 of the node-articles-nlp/node_modules/bson/ext/index.js file.
